spring:
  redis:
    database: 0
    host: 172.27.174.3
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.108:1521:orcl
    username: system
    password: admin
  jpa:
    database: oracle
    show-sql: true
server:
  port: 8081